#Type Name       ID             GECOS                                        Home directory    Shell
u     container  1000:1000      "Basic user for running container workloads" /home/container   /usr/bin/bash
g     container  1000