name: Build and push container image

on:
  schedule:
    - cron: '25 19 * * 0'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: toby-st/basic-bootc-host


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against the container registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: podman login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      # Build the image with buildah
      # https://github.com/redhat-actions/buildah-build
      - name: Build container image with buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: ./Containerfile
          oci: true

      # Push and sign with podman except on PR
      - name: Push and sign container image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.KEY_2025_11_B64 }}
        run: |
          mkdir -p ~/.config/containers/registries.d
          cp config/registries.d.yaml ~/.config/containers/registries.d/ghcr.io-toby-st.yaml
          echo "${COSIGN_PRIVATE_KEY}" | base64 -d > /tmp/cosign.key
          for TAG in latest ${{ github.sha }}; do
            podman push \
              --sign-by-sigstore-private-key /tmp/cosign.key \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG}
          done
          rm -f /tmp/cosign.key
